#! /bin/bash

usage() {
  echo "Usage: dev [subcommand]"
  echo ""
#  echo "all       Run everything (the default)"
#  echo "ext       Run just the services (not the app)"
  echo "app       Run just the app (not any services)"
  echo "help      Print this usage"
  exit 2
}

#run_all () {
#  concurrently --names "REDIS,APP" --prefix-colors "blue,green" "npm run redis-dev" "npm run watch-dev" 
#}

#run_services () {
#  concurrently --names "REDIS" --prefix-colors "blue" "npm run redis-dev"
#}

run_app () {
  npm run watch-dev
}

case "$1" in
  help)   usage ;;
  #all)    run_all ;;
  #ext)    run_services ;;
  #app)    run_app ;;
  *)      run_app ;;
esac
